setwd("~/Desktop/pcl/2/svm/SVM_in_R")
library(e1071)
hist=read.csv2("1.csv",header=FALSE,sep=' ',stringsAsFactors = FALSE)
hist=lapply(hist,as.numeric)
#hist=data.frame(hist1,hist2)
class=read.csv("class1.csv")
hist=data.frame(hist,Class=class$Class)
library(caTools)
set.seed(123)
sample=sample.split(hist$Class,SplitRatio = 0.70)
train=subset(hist,sample==TRUE)
test=subset(hist,sample==FALSE)
test_class=test$Class
test$Class=NULL
#mytunedsvm <- tune.svm(Class~., data = train, gamma = 2^(-1:1), cost = 2^(2:4)) 
#mytunedsvm <- tune.svm(Class~., data = train, gamma = 10^(-6:-2),  cost = 10^(1:3)) 
#mytunedsvm <- tune.svm(Class~., data = train, gamma = 2^(-14),  cost = 4 )
#mytunedsvm <- tune.svm(Class~., data = train, gamma = 10^(-6:-2),  cost = 10^(1:2)) 
#mytunedsvm <- tune.svm(Class~., data = train, cost=10^(-2:3), gamma=2^(-16:4)) 
#summary(mytunedsvm)
#plot (mytunedsvm, transform.x=log10, xlab=expression(log[10](gamma)), ylab="C")
#plot (mytunedsvm)
#model=svm(Class~.,data=train,type='C-classification')
#model=svm(Class~.,data=train,type='C-classification',cost=mytunedsvm$best.parameters[[2]],gamma=mytunedsvm$best.parameters[[1]], probability= TRUE)
model=svm(Class~.,data=train,type='C-classification',cost=10^(2),gamma=8, probability= TRUE)
#prediction=predict(model,newdata = test)
#prediction=predict(model,newdata = test,cost=mytunedsvm$best.parameters[[2]],gamma=mytunedsvm$best.parameters[[1]], probability = TRUE)
prediction=predict(model,newdata = test,cost=10^(2),gamma=8, probability = TRUE)
#summary(model)
summary(prediction)
attr(prediction, "probabilities")
out <- capture.output(attr(prediction, "probabilities"))

cat( out, file="svm10.txt", sep="\n")
#table(prediction,test_class)
library(caret)
confusionMatrix(test_class, prediction)
